version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9050:9050"
    environment:
      SPRING_APPLICATION_NAME: TaskManager
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TaskManager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123324
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: true
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: TaskManager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123324
    ports:
      - "5433:5432"